### ISSUE TITLE
commands not working for invited bot

### ISSUE THREAD

**Issue by IdaWW** [i-hardy/woolf#1]
Hi, I invited the bot to the server, but none of the commands work? is there any issues or do I need to give the bot some special permissions? thanks!

**Comment by Stargazerlilith** [comment]
I just invited the bot into a new server today and I am having the same issue. I have used the bot before and never had this happen in a different server.  the only command that is working is @woolf.   Hopefully it will get fixed soon.

**Comment by i-hardy** [comment]
@IdaWW @Stargazerlilith I am looking into an issue a few people have reported with the bot receiving a permissions-related error from Discord even when the correct permissions are set, which prevents sprints from working correctly. I've made a quick patch change tonight to attempt to handle this, and you should now at least be able to use the other functions of the bot even if sprints aren't working correctly.
